### PR TITLE
Feature linter

### PR DESCRIPTION
**Pull request by AdesojiCodeMaster**
## This is a custom linter project to inspect errors in the codes within files according to built-in logic.

### CODE REVIEW

**Comment by AdesojiCodeMaster** [comment]
## This is to request the code review for my project;

### The Project Title:**My_Linter_Capstone_project.**

### The Author: **Adesoji**

[Video Link](https://www.loom.com/share/e86a5e6d32e947e8bc7d6d4104977bb3)

This project was built with;
## Ruby
Other technology/gem used;
### colorize
### Rubocop
### Rspec

#### Thank You for taking the time to review my code. 💐

Thanks!

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

Thank you for applying the suggested changes.
However, integrations tests are missing. Please, can you add them for friendship? 

Thank you.

Mael FOSSO

**Comment by AdesojiCodeMaster** [comment]
## This is to request for a new code review for my project;
## The corrections have been made according to the TSEs recommendations
### The Project Title: **My_Linter_Capstone_project.**

### The Author: **Adesoji**

[Video Link](https://www.loom.com/share/e86a5e6d32e947e8bc7d6d4104977bb3)

This project was built with;
## Ruby
Other technology/gem used;
### colorize
### Rubocop
### Rspec

#### Thank You for taking the time to review my code. 💐

Thanks!

**Comment by AdesojiCodeMaster** [comment]
## This is to request for a new code review for my project;
## The corrections have been made according to the TSEs recommendations
#### 1. Gems added to the Gemfile.
#### 2. Rspec worked upon to pass all the test cases.
### The Project Title: **My_Linter_Capstone_project.**

### The Author: **Adesoji**

[Video Link](https://www.loom.com/share/e86a5e6d32e947e8bc7d6d4104977bb3)

This project was built with;
## Ruby
Other technology/gem used;
### colorize
### Rubocop
### Rspec

#### Thank You for taking the time to review my code. 💐

Thanks!

**Pull request merged**
